environment:
  FLUTTER_SDK_PATH_WITH_SPACE: "flutter sdk"
  BOT: "true"

container:
  image: cirrusci/flutter:latest

test_task:
  pub_cache:
    folder: ~/.pub-cache
  test_script: flutter test -machine > report.json
  always:
    report_artifacts:
      path: report.json
      format: flutter